# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: windysl
          password: 19970317winindee
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: windysl/django_backend:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run: docker tag windysl/django_backend:latest registry.digitalocean.com/django-backend

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/django-backend

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: 178.128.121.215
          USERNAME: root
          KEY: ${{ secrets.SSHKEY }}
          script: |
            # Stop running container
            docker stop django

            # Remove old container
            docker rm django

            # Run a new container from a new image
            docker run --name django -p 8000:8000 windysl/django_backend
